volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:

services:
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ../backend:/workspaces/backend:cached
    command: sleep infinity
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - .env
    network_mode: service:db

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - .env

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - .env